name: Run Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
  workflow_dispatch:

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build
          env: CI=false

      # report machine parameters
      - run: yarn cypress info
      - run: node --version
      - run: node -p 'os.cpus()'

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  install-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build
          env: CI=false

      # report machine parameters
      - run: yarn cypress info
      - run: node --version
      - run: node -p 'os.cpus()'

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Node info
        run: node -v

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          #record: true
          parallel: true
          group: "UI - Chrome"
          component: true

  ui-firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    needs: install
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: firefox
          #record: true
          parallel: true
          group: "UI - Firefox"
          component: true

  ui-windows-tests:
    timeout-minutes: 40
    runs-on: windows-2022
    needs: install-windows
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: "UI Tests - Electron - Windows"
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          #record: true
          parallel: true
          group: "UI - Electron - Windows"
          component: true
